// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8TeVsHVztKrvQIFWR1wTAy53me8TURv0',
    appId: '1:715813061643:web:dfdd08663996f93460730e',
    messagingSenderId: '715813061643',
    projectId: 'chatapp-a2167',
    authDomain: 'chatapp-a2167.firebaseapp.com',
    storageBucket: 'chatapp-a2167.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6E8fVXCjoWCo-COmSocaO3vdfRlsf5So',
    appId: '1:715813061643:android:44b609a9e93d82fd60730e',
    messagingSenderId: '715813061643',
    projectId: 'chatapp-a2167',
    storageBucket: 'chatapp-a2167.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQR9Mhou2Xi6Skr7M7ZW20Ngimw_AB9K0',
    appId: '1:715813061643:ios:dbf0cf92740c359c60730e',
    messagingSenderId: '715813061643',
    projectId: 'chatapp-a2167',
    storageBucket: 'chatapp-a2167.appspot.com',
    iosBundleId: 'com.example.msgApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQR9Mhou2Xi6Skr7M7ZW20Ngimw_AB9K0',
    appId: '1:715813061643:ios:dbf0cf92740c359c60730e',
    messagingSenderId: '715813061643',
    projectId: 'chatapp-a2167',
    storageBucket: 'chatapp-a2167.appspot.com',
    iosBundleId: 'com.example.msgApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8TeVsHVztKrvQIFWR1wTAy53me8TURv0',
    appId: '1:715813061643:web:fde500053781ca1560730e',
    messagingSenderId: '715813061643',
    projectId: 'chatapp-a2167',
    authDomain: 'chatapp-a2167.firebaseapp.com',
    storageBucket: 'chatapp-a2167.appspot.com',
  );
}
